matrix:
  include:
    - os: windows
      language: cpp
      install: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

script:
  - cd Plugins/Cesium/ThirdParty/cesium-native
  - pushd extern; mkdir build; cd build; mkdir draco; cd draco
  - cmake ../../draco/ -G "Visual Studio 16 2019"
  - cmake --build . --config Release
  - popd
