matrix:
  include:
    - os: windows
      language: cpp

script:
  - cd Plugins/Cesium/ThirdParty/cesium-native
  - pushd extern; mkdir build; cd build; mkdir draco; cd draco
  - cmake ../../draco/ -G "Visual Studio 16 2019"
  - cmake --build . --config Release
  - popd