language: cpp
matrix:
  include:
    - os: windows
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install doxygen.install
    - os: linux
      dist: bionic
      install:
        - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
        - sudo apt-get update
        - sudo apt-get install cmake
        - export PATH=/usr/bin:$PATH

script:
  - cd Plugins/Cesium/ThirdParty/cesium-native
  - cd extern
  - ./build.sh
  - cd ..
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . --config Debug
  - cd test
  - ctest -V
  - cmake --build . --config Debug --target cesium-native-docs
